language: python
python:
- "2.7"
# command to install dependencies
install:
- pip install pytest pytest-cov
- pip install mockito
- pip install pep8
- pip install radon
- pip install coveralls
# command to run tests
script:
- py.test --cov . --cov-report term-missing
after_success:
    - pep8 --statistics -qq tests
    - pep8 --statistics -qq src
    - coveralls
    - radon cc tests , src
    - radon raw tests , src
    - radon raw src
    - radon mi tests
    - radon mi src
notifications:
  email:
    recipients:
      - lemmechange@insibera.net
    on_failure: always
    on_success: never
